name: Publish to GitHub Pages

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - feature/documentation

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn install

      - name: Build @igloo-ui/tokens
        run: yarn build

      - name: Generate your awesome content
        run: yarn build-storybook

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: storybook-static
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
