name: Publish to GitHub Pages

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - feature/documentation

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 12
      -  run: yarn install
      -  run: yarn lint

      - name: Generate your awesome content
        run: yarn build-storybook

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: storybook-static
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}